repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Latest stable version as of now
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Replace with the latest stable version of mypy
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]  # Optional: Ignore imports for libraries without type hints
